### ISSUE TITLE
Perl Scan Failing

### ISSUE THREAD

**Issue by lalitkhatri1** [sonar-perl/sonar-perl#100]
While running Sonar Scan for perl, having below issue:
11:33:04.580 ERROR: Error during SonarQube Scanner execution
java.lang.IllegalArgumentException: Unable to highlight file environment/dbatch/system/perl5/i386.b/lib/5.18.0/CPANPLUS/Internals/Constants/Report.pm

can someone help ?

**Comment by otrosien** [comment]
Which version of sonar-perl are you using? Can you paste the contents of the file and try to produce a stack trace for easier analysis?

**Comment by LMenegoni** [comment]
I am having the same issue with : 

Version | 7.9.1.27448
Database | Microsoft SQL Server
Database Version | 12.00.5579
Driver | Microsoft JDBC Driver 7.2 for SQL Server-- | --
Driver Version | 7.2.2.0
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)-- | --


--

**Comment by alepulver** [comment]
Hi, a `.pm` file with the following lines triggers the problem. It seems there is an empty token being parsed.

```
$x = 1 << $x;
$x = 1 << $x;
```

The stacktrace is:

```
Caused by: java.lang.IllegalArgumentException: Unable to highlight file lib/MyFile.pm
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:97)
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:37)
	at com.github.sonarperl.highlighter.PerlHighlighter.highlight(PerlHighlighter.java:66)
	... 40 more
Caused by: java.lang.IllegalArgumentException: Start pointer [line=2, lineOffset=0] should be before end pointer [line=2, lineOffset=0]
	at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRangeValidPointers(DefaultInputFile.java:325)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:263)
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:95)
	... 42 more
```

**Comment by otrosien** [comment]
The parsing is best-effort, especially problematic in complex parsing cases like heredocs or POD. Please check the latest release (0.5.2) if that solves your issue.
