### ISSUE TITLE
Projects with mixed file encoding cause sonar-scanner to fail

### ISSUE THREAD

**Issue by otrosien** [sonar-perl/sonar-perl#41]
In the following log output a utf-8 file is used inside an iso-8859-1 based project. If possible, this should not cause the sonar scan to fail.

```
INFO: Scanner configuration file: /opt/sonarscanner/sonar-scanner-2.8/conf/sonar-scanner.properties
INFO: Project root configuration file: /srv/epages/eproot/Cartridges/DE_EPAGES/Address/sonar-project.properties
INFO: SonarQube Scanner 2.8
INFO: Java 1.8.0_111 Oracle Corporation (64-bit)
INFO: Linux 3.10.0-327.36.3.el7.x86_64 amd64
INFO: User cache: /root/.sonar/cache
INFO: Load global repositories
INFO: Load global repositories (done) | time=201ms
INFO: User cache: /root/.sonar/cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=43ms
INFO: SonarQube server 6.2
INFO: Default locale: "de_DE", source code encoding: "ISO-8859-1"
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=111ms
INFO: Execute project builders
INFO: Execute project builders (done) | time=1ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=36ms
INFO: Load active rules
INFO: Load active rules (done) | time=517ms
INFO: Publish mode
INFO: -------------  Scan DE_EPAGES::Address
INFO: Load server rules
INFO: Load server rules (done) | time=154ms
INFO: Initializer GenericCoverageSensor
INFO: Initializer GenericCoverageSensor (done) | time=0ms
INFO: Base dir: /srv/epages/eproot/Cartridges/DE_EPAGES/Address
INFO: Working dir: /srv/epages/eproot/Cartridges/DE_EPAGES/Address/.sonar
INFO: Source paths: API, DAL, Scripts
INFO: Test paths: t
INFO: Source encoding: ISO-8859-1, default locale: de_DE
INFO: Index files
INFO: 23 files indexed
INFO: Quality profile for perl: Sonar way
INFO: Sensor Lines Sensor
INFO: Sensor Lines Sensor (done) | time=11ms
INFO: Sensor org.sonar.plugins.clover.CloverSensor
WARN: Clover XML report not found
INFO: Sensor org.sonar.plugins.clover.CloverSensor (done) | time=0ms
INFO: Sensor SCM Sensor
INFO: Sensor SCM Sensor (done) | time=11ms
INFO: Sensor Coverage Report Import
INFO: Sensor Coverage Report Import (done) | time=0ms
INFO: Sensor Coverage Report Import
INFO: Sensor Coverage Report Import (done) | time=0ms
INFO: Sensor Unit Test Results Import
INFO: Sensor Unit Test Results Import (done) | time=0ms
INFO: Sensor XmlFileSensor
INFO: Sensor XmlFileSensor (done) | time=0ms
INFO: Sensor Perl Sensor
INFO: Sensor Perl Sensor (done) | time=148ms
INFO: Sensor PerlCritic Sensor
INFO: Configured report path: sonar_perlcritic_report.txt
INFO: PerlCritic report file 'sonar_perlcritic_report.txt' does not exist. Skipping...
INFO: Sensor PerlCritic Sensor (done) | time=2ms
INFO: Sensor Perl Test::Harness Sensor
INFO: Configured report path: sonar_test_report.tgz
INFO: Reading file entry meta.yml from archive.
INFO: Sensor Perl Test::Harness Sensor (done) | time=122ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=28ms
INFO: Sensor Code Colorizer Sensor
WARN: Unable to perform colorization of file /srv/epages/eproot/Cartridges/DE_EPAGES/Address/t/HouseNumber.t
java.lang.IllegalArgumentException: Unable to highlight file [moduleKey=DE_EPAGES::Address, relative=t/HouseNumber.t, basedir=/srv/epages/eproot/Cartridges/DE_EPAGES/Address]
                at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:84)
                at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:36)
                at org.sonar.scanner.source.HighlightingCodeBuilder.appendWithoutTransforming(HighlightingCodeBuilder.java:73)
                at org.sonar.colorizer.KeywordsTokenizer.consume(KeywordsTokenizer.java:69)
                at org.sonar.colorizer.KeywordsTokenizer.consume(KeywordsTokenizer.java:33)
                at org.sonar.colorizer.TokenizerDispatcher.colorize(TokenizerDispatcher.java:50)
                at org.sonar.scanner.source.HighlightingRenderer.render(HighlightingRenderer.java:40)
                at org.sonar.scanner.source.CodeColorizers.toSyntaxHighlighting(CodeColorizers.java:86)
                at org.sonar.scanner.source.CodeColorizerSensor.execute(CodeColorizerSensor.java:60)
                at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
                at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
                at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
                at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
                at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
                at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
                at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
                at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
                at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
                at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
                at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
                at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
                at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
                at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
                at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
                at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
                at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
                at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
                at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
                at com.sun.proxy.$Proxy0.execute(Unknown Source)
                at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
                at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
                at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
                at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
                at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.IllegalArgumentException: 6467 is not a valid offset for file [moduleKey=DE_EPAGES::Address, relative=t/HouseNumber.t, basedir=/srv/epages/eproot/Cartridges/DE_EPAGES/Address]. Max offset is 6435
                at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
                at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:268)
                at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:263)
                at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:82)
                ... 38 common frames omitted
```

**Comment by otrosien** [comment]
I posted that on SonarQube google group, unfortunately so far without answer.
https://groups.google.com/d/msg/sonarqube/iDoheviKZ20/VTtQPKFWDgAJ

**Comment by otrosien** [comment]
The highlighter engine has been removed from sonarqube 6.4, so this issue will also go away once we upgrade...

**Comment by otrosien** [comment]
Fixed via https://github.com/sonar-perl/sonar-perl/commit/e1ff1a50b0571163507a39021fd2b4bb73233368.
